### ISSUE TITLE
same question repeated during gameplay

### ISSUE THREAD

**Issue by zoiteki** [cschmidt0121/qad_custom#3] opened 2024-04-12 21:57 UTC
Hello! I am very happy to have found this project, thanks for working on it!

I've been struggling at getting it working, however. I'm able to download questions from OpenTDB just fine and run the build. As far as I can see, the rom is patched successfully.

However, when I load it into MAME (or my MiSTer), while the game runs successfully, I am faced with the same question over and over while playing. 

It isn't clear if there's something I'm doing incorrect or a way for me to debug. I'd be happy to provide whatever information is necessary if it would help resolve the issue!

**Comment by EverdredIIDX** [comment] 2024-04-12 22:00
That’s odd. I won’t be able to look into this for a bit but I will when I am able.

**Comment by USAvery** [comment] 2024-04-19 04:51
I'm having the same error myself. Been trying to debug it for a few days lol

**Comment by USAvery** [comment] 2024-04-22 19:13
I figured it out how to get it working! 
After all that digging, it was just that there weren't enough questions. 
When building **questions.json** in **opentdb.py**, it  only generated 2196 questions.
I figured it out by writing a script to extract all the questions in the game. Then I reinjected them and it worked.

Then I decided to rework **opentdb.py** to combine different OpenTDB categories. 
With that, I was able to get it to use almost all the questions from OpenTDB.
Building it with the larger number of questions got rid of the repetition error.

I'm sure there is a cleaner way to get it working with less questions. 
I'll have to run some more tests for that. But at least it's working now.

**Comment by EverdredIIDX** [comment] 2024-05-04 12:52
Thanks a ton @USAvery for the extra info on this. I don't remember this being an issue (in fact I'm pretty sure I remember testing with just a handful of questions), but I'm going to look into it and see there's a better solution.

**Comment by EverdredIIDX** [comment] 2024-05-04 15:58
Okay, I've narrowed this down. This is being caused by the category names (stored in ROM starting at 0x1dc1e) overflowing into the category question-counts (stored in ROM starting at 0x1dc9a). This causes the game to attempt to load in questions that don't exist, resulting in corrupted questions.

The easy fix for this is to just limit the total length of question names, but I'm going to see if I can maybe just move the question counts somewhere else and update pointers in order to free up room.

**Comment by EverdredIIDX** [comment] 2024-05-05 02:17
I ended up giving up on the hard fix and just went for the easy one. Trying to redirect pointers led to more issues that I don't want to try and figure out. If anyone wants to try and do that, be my guest :) 

The latest commit shortens some category names and adds validation to prevent this from happening in the future. Thanks for the heads up!

**Closed as completed by EverdredIIDX** 2024-05-05 02:17 UTC
